export const ENABLED_PROBES = {
  runtimeSurface: false,
  enums: false,
  hotbar: false,
  clipboardCursor: false,
  clipboardCursorWatch: false,
  blueprints: false,
  blueprintReads: false,
  catalog: true,
  catalogReads: true,
  knownStructureDefinitions: true,
  structureCatalog: true,
  clipboard: false,
  clipboardReads: false,
} as const;
